
[jobs.3ds-check]
command = ["cargo", "3ds", "check"]
need_stdout = true
allow_warnings = true

[jobs.3ds-check-examples]
command = ["cargo", "3ds", "check", "--examples"]
need_stdout = true
allow_warnings = true
watch = ["examples"]


[jobs.bacon-ls]
command = [
    "cargo",
    "3ds",
    "check",
    # "--examples",
    "--message-format",
    "json-diagnostic-rendered-ansi",
]
analyzer = "cargo_json"
need_stdout = true
watch = ["examples"]

[exports.cargo-json-spans]
auto = true
exporter = "analyzer"
line_format = "{diagnostic.level}|:|{span.file_name}|:|{span.line_start}|:|{span.line_end}|:|{span.column_start}|:|{span.column_end}|:|{diagnostic.message}|:|{diagnostic.rendered}|:|{span.suggested_replacement}"
path = ".bacon-locations"
